### ISSUE TITLE
Error message: `Cannot destructure property `encode` of 'undefined' or 'null'.`

### ISSUE THREAD

**Issue by lapanoid** [nars-dev/nars#27]
I was going through install steps here https://github.com/nars-dev/nars#getting-started-with-examples, and on 
`cd examples/server && yarn start` step
I have message 
```
/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:1
parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(funct

TypeError: Cannot destructure property `encode` of 'undefined' or 'null'.
    at Object.optional (/Users/sergeylapin/repos/private/nars/examples/server/node_modules/nars-common/dist/ComponentConfig.js:12:16)
    at Object.parcelRequire.QrU2 (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:6:144)
    at f (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:1:468)
    at p (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:1:544)
    at Object.parcelRequire.zo2T../Form (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:20:218)
    at f (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:1:468)
    at parcelRequire.yvO7 (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:1:771)
    at Object.<anonymous> (/Users/sergeylapin/repos/private/nars/examples/server/dist/index.js:1:1023)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
error Command failed with exit code 1.
```

**Comment by wokalski** [comment]
I'm looking at it 👀.

**Comment by wokalski** [comment]
https://github.com/nars-dev/react-day-berlin-2019-demo 
Did you try this? Does it give the same error?

**Comment by lapanoid** [comment]
here I have error 
```
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
```
on running 
```
cd react-day-berlin-2019-demo/client && yarn
```

**Comment by wokalski** [comment]
Thank you. I'll fix it asap.

**Comment by wokalski** [comment]
This issue has been fixed. I'm cloning and testing examples from scratch now, thank you! I cannot reproduce the issue from the react day berlin demo repo :(.

Feel free to try again, maybe the registry was simply down 🙃
